# You can set these variables from the command line.
SPHINXOPTS    =
SPHINXBUILD   = sphinx-build
SPHINXPROJ    = vgio
SOURCEDIR     = .
BUILDDIR      = _build

.PHONY: build clean

build:
	sphinx-build -M html . _build

clean:
	rm -rf _build
